### ISSUE TITLE
how to download MAG?

### ISSUE THREAD

**Issue by VladimirAlexiev** [sandrolabruzzo/doiBoost#2]
Can you describe in more detail how to download MAG, since the paper gives only a general link to https://azure.microsoft.com/en-us/services/storage/data-lake-storage?
I know a part of it can be downloaded from https://www.openacademic.ai/oag/, but that's a snapshot from 2017-06-09 (a bit old).

Thanks!

**Comment by VladimirAlexiev** [comment]
I guess this is a better link? https://docs.microsoft.com/en-us/academic-services/graph/get-started-setup-provisioning

**Comment by sandrolabruzzo** [comment]
Yes it is the right place to start to download MAG.
