### ISSUE TITLE
what do you mean by "enriched DOIs"?

### ISSUE THREAD

**Issue by VladimirAlexiev** [sandrolabruzzo/doiBoost#5]
In Table 2 you say that 74,582,104 MAG DOIs have "enriched" 67,879,513 CrossRef DOIs.
I understand what you mean by "enrichment" for the other fields, but what do you mean by "enriched" regarding DOIs?

**Comment by sandrolabruzzo** [comment]
This number means that in MAG we have 74,582,104 of Paper with DOI.
This number 67,879,513 is the intersection between MAG and CrossRef, and that means that these crossref Items will be enriched by some info from MAG

**Comment by VladimirAlexiev** [comment]
Thanks! So that's intersection, that line doesn't mean the CrossRef record was changed.
